### ISSUE TITLE
RFID Module Driver

### ISSUE THREAD

**Issue by MacRush7** [cu-ecen-5013/final-project-assignment-sast7580#10]
**Task:** Develop an interface for connecting the RFID sensor with the BBB. The RFID sensor should be able to sense an RFID card and demand for a user name after successfully detecting and storing the unique user-specific RFID card details on the BBB for user identification and authentication purposes. The data may be used by other processes running on the BBB.

**Description:** The RFID sensor that is required to be connected with the BBB which can be found on [Amazon Webpage](https://www.amazon.com/IZOKEE-RFID-RC522-13-56MHz-Arduino-Raspberry/dp/B076HTH56Q/ref=asc_df_B076HTH56Q/?tag=hyprod-20&linkCode=df0&hvadid=309750549985&hvpos=1o1&hvnetw=g&hvrand=15834435632643179495&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1014448&hvtargid=pla-564122493348&psc=1). The RFID sensor requires an SPI connection with the BBB for running the scripts from the BBB user-space to detect an RFID card and to save the associated user's name. Furthermore, if the card is already known, the user receives an access to the system (at this time - the definition of access to the system is limited to a successful authentication message on the terminal). If the detected card is unknown, the new unique card details are stored and the system will ask for the associated user's name. Eventually, the data collected by the BBB from the RFID sensor is stored with the user name associated with the card in a file on the BBB. The stored data in the file may be used by some other process running on the BBB.

**Open-source references:**

| Hardware Interface   | Open-source project reference links                                 | Packages to be included |
| -------------------- | ------------------------------------------------------------------- | ----------------------- |
| BBB - RFID sensor             | References: [1](http://papermint-designs.com/community/node/394), [2](http://papermint-designs.com/community/node/218), [3](https://github.com/ondryaso/pi-rc522/blob/master/README.md), [4](https://github.com/farm2440/rfid), [5](https://github.com/farm2440/rfid), [6](https://pimylifeup.com/raspberry-pi-rfid-rc522/) | NA |

**Repository:** [Source Application Repository](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7)

**DoD:** The following set of tasks will have to be successfully performed as a definition of done:

1. Log "RFID sensor connected" when the RFID sensor is connected with the BBB and the init script is run.
2. Log "RFID sensor not detected" upon system startup if the RFID sensor is not connected and/or the user requests from the user-space terminal for RFID sensor service termination.
3. Log "RFID sensor disconnected" upon request from the user-space using the terminal for the service termination and successful detection of the RFID sensor connection with the BBB.
4. Log "User detected..." when the RFID sensor is connected to the BBB and a unique card is pressed against the sensor.
5. Log "Unique card temporarily stored" when the RFID sensor is connected to the BBB and a unique card is detected and the associated information is stored by the BBB.
6. Log "Enter user name" when the RFID sensor is able to successfully store the unique card details collected by the sensor specific to a user for which the BBB will ask for a user name without which the system would drop the stored RFID card details. 
7. Log "Unique RFID card added" when the unique RFID card is permanently stored and a user name is successfully attached with it by the BBB while there is a successful connection with the RFID sensor.
8. Log "Type user name to delete data" when the user requests from the command line to delete the RFID card data associated with a particular user name.

**Comment by MacRush7** [comment]
**Issue Updates:** _I could not complete interfacing the RFID with my BBB. However, I was able to find good resources: [1](https://elinux.org/BeagleBone_Black_RFID_Adaptor_Cape) and [2](https://elinux.org/BeagleBone_Black_Enable_SPIDEV) that were helpful. Based on these resources, I will be able to establish an SPI connection with BBB for the RFID sensor in sprint-2 and test the framework by referencing the open-source work provided in resources. At this time, there has been no progress on this issue that can be validated unlike the issue on MySQL and so I will be moving this issue to Sprint-2. Thanks.

**Comment by MacRush7** [comment]
**Issue Updates:** There was a build error for buildroot after enabling the Python3-SPIDEV library. I was required to clean and build again since it was required. But, then I again faced the Git TI server connection problem as I was facing previously. For the time being, I have added python scripts that can be tested using the rfidtest.sh script (but on a RPi) to showcase that the RFID sensor meets the DoD. The scripts can be found [here](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/tree/master/rfid-test).

Once the build succeeds for Buildroot, I can test the same scripts on the BBB after transferring the RPI.GPIO library as a module for Buildroot. I am marking this issue complete and closing it based on my understanding since my blocker is related with a failing build. Please, let me know if I should reopen it. Thanks.

**Comment by dwalkes** [comment]
@MacRush7 based on a quick glance at https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/blob/master/rfid-test/Read.py and https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/blob/master/rfid-test/Write.py it doesn't look like you've really implemented the DoD.  For instance, "RFID Sensor Connected" [here](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/blob/master/rfid-test/Write.py#L10) will be printed whenever the script is run, not related to whether a sensor was actually connected.

I'd recommend rewriting the DoD to match what you actually implemented/tested with this release and associated scripts.

**Comment by MacRush7** [comment]
@dwalkes Thanks for pointing it out. I realize I could not implement that since my build.sh was failing. If it had worked, I could have tested it for specific pins on the BBB. 

My plan was to add RFID modules to buildroot and add an init script for checking specific GPIO pins if the sensor was connected when the BBB was powered up. But, as my build.sh was failing due to the problem mentioned [here](https://github.com/cu-ecen-5013/final-project-assignment-sast7580/tree/master/Buildroot_Issues), I implemented and tested the script for an RPI platform with Python support. Because the pins would change on the BBB, I did not explicitly implement a feature there for checking if the sensor was physically connected. However, if at all the sensor is not physically connected, the script won't run successfully. Based on the current script, it will wait until the sensor is connected and the user is ready to let their RFID card be scanned.

**Comment by steveantony5** [comment]
@MacRush7  I couldn't find any code for RFID sensor in the folder RFID driver. What is the status?
Also I could see some code in the folder RFID_Test in python. Is that the source code?

**Comment by MacRush7** [comment]
@steveantony5 I have added the python-based source code for testing the RFID sensor [here](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/tree/master/rfid-test). The [rfidtest.sh](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/blob/master/rfid-test/rfidtest.sh) script runs based on the other two python scripts: [Read.py](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/blob/master/rfid-test/Read.py) and [Write.py](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/blob/master/rfid-test/Write.py). The test script demonstrates the use of an RFID sensor on an RPI. Again, this was because of the fact that there were issues building Buildroot because of the problem that I was facing with the git ti server on my VM. I could not test the RFID sensor on the BBB node and therefore, I tested the python-based source files with the test script on an RPi running Raspbian. The status shows that the RFID sensor works and senses for any RFID card registration and reads out the card name (which the user enters at the beginning while running the test script) and the card unique ID. This demonstrates the use of the RFID sensor within the scope of the project and shows how it will be integrated for sprint-3 and project demo. Also, please note that the script would not run if the sensor is physically disconnected (consistent with the DoD).

As for [rfid-driver](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/tree/master/rfid-driver) directory that was added to the source repository, I apologize for it since it does not contain any relevant source code as I was unable to test the Buildroot build because of the failed builds. Please, ignore the same for sprint-2 grading and consider the python-based source code for testing the RFID sensor which can be found [here](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/tree/master/rfid-test).

Please, let me know if you have any queries on the work done for sprint-2. Thanks.

**Comment by steveantony5** [comment]
@MacRush7  So the status of this work is that the sensor works only on Rpi. You are now trying to make it work on buildroot BBB. Am I right? Also are you planning to have python code or C code for BBB?

**Comment by MacRush7** [comment]
@steveantony5 Yes, you are correct. I am now implementing it to work with Buildroot. I feel I found more python-based open-source projects than for c code. But, since I will be working with Buildroot, I think I will have a mix of the two at the end. At least for the RFID sensor, I am planning to use python.
