### ISSUE TITLE
Fingerprint Module Driver: Sprint 2

### ISSUE THREAD

**Issue by sast7580** [cu-ecen-5013/final-project-assignment-sast7580#11]
**Task:** Develop an interface for connecting the Fingerprint sensor with the BBB. The Fingerprint sensor should be able to capture fingerprint images and successfully send the images to the BBB which should be able to successfully store the unique user-specific fingerprints for identification and authentication purposes.

**Finished** Userspace code complete.  Button and led interface operates correctly.

**Description:** The Fingerprint sensor that is required to be connected with the BBB can found on [Sparkfun Webpage](https://www.sparkfun.com/products/15338). The Fingerprint sensor requires a UART connection via HAL with the BBB to run commands to capture unique user-specific fingerprints when a user is detected on the sensor. Eventually, the data collected by the BBB from the Fingerprint sensor as unique images will be stored in a file on the BBB. The stored data may be used by some other process running on the BBB.

**Open-source references:** 

| Hardware Interface   | Open-source project reference links                                 | Packages to be included | Implementation Details |
| -------------------- | ------------------------------------------------------------------- | ----------------------- | ------------ |
| BBB - Fingerprint sensor             | References: [1]() | NA | [Page]() |

**Repository:** [Source Application Repository](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7)

**DoD:** The following set of tasks will have to be successfully performed as a definition of done:

1. Log "Fingerprint sensor connected" when the Fingerprint sensor is connected with the BBB and the init script is run.
2. Log "Fingerprint sensor disconnected" upon request from the user-space using the terminal for the service termination and successful detection of the Fingerprint sensor connection with the BBB.
3. Log "User detected..." when the Fingerprint sensor is connected to the BBB and a user finger is pressed against the sensor.
4. Log "Unique fingerprints temporarily stored" when the Fingerprint sensor is connected to the BBB and multiple user fingerprints are collected by the sensor and the user-specific unique fingerprints are stored on the BBB.
6. Log "Unique fingerprints added" when the unique fingerprints are permanently stored and a user name is successfully attached with it by the BBB while there is a successful connection with the Fingerprint sensor.

**Still Needs to be Done**
5. Log "Enter user name" when the Fingerprint sensor is able to successfully store the unique fingerprints collected by the sensor specific to a user for which the BBB will ask for a user name without which the system would drop the stored fingerprints. 
7. Log "Type user name to delete data" when the user requests from the command line to delete the fingerprint data associated with a particular user name.

**Comment by steveantony5** [comment]
@sast7580  Block diagram says that finger print sensor will be interfaced with BBB. But the issue says it would be interfaced with RPi.

**Comment by sast7580** [comment]
Sprint 2 finished.  Moving remaining to be done to Sprint 3.

**Comment by steveantony5** [comment]
@sast7580  Does the above said functionalities work on buildroot or just on the standard linux?

**Comment by sast7580** [comment]
The buzzer module does... I havent tested the fingerprint sensor yet.
