### ISSUE TITLE
Kernel Transfer

### ISSUE THREAD

**Issue by sast7580** [cu-ecen-5013/final-project-assignment-sast7580#2]
**Task:** Add custom Linux kernel to the SD card for the Beaglebone Black (BBB) hardware platform using Buildroot build system.

**Description:** The [Beaglebone Black Hardware Support](https://github.com/cu-ecen-5013/buildroot-assignments-base/wiki/Beaglebone-Black-Hardware-Support) page provides a brief description for bringing up the BBB hardware platform. In general, The _**Beagle Bone Black**_ hardware platform should successfully run the Linux kernel version as supported on the [Buildroot Repository](https://github.com/cu-ecen-5013/final-project-assignment-sast7580). The hardware platform must demonstrate a root filesystem as built by the Buildroot build system and should allow for an Ethernet connection.

**DoD:** The following set of tasks will be successfully performed in this issue on an individual basis:

1. Run build.sh script using the Buildroot build system files available at [Buildroot Repository](https://github.com/cu-ecen-5013/final-project-assignment-sast7580) and generate a sdcard.img in the buildroot/output/images/ directory.
2. Flash the sdcard.img image file into the SD card for the BBB.
3. Boot the BBB device from the SD card.
4. Establish connection with BBB through Ethernet.

**Comment by dwalkes** [comment]
@MacRush7 please add the DoD to the description of the task rather than in the comments

**Comment by MacRush7** [comment]
**Updates:** _Completed kernel transfer for my Beaglebone Black. Can run the same instance as can be seen on my QEMU. Successfully tested "lsmod" command and can see aesdchar and ldd-modules running on my BBB._
