### ISSUE TITLE
Fingerprint Module

### ISSUE THREAD

**Issue by sast7580** [cu-ecen-5013/final-project-assignment-sast7580#4]
**Task:** Develop an interface for connecting the Fingerprint sensor with the BBB. The Fingerprint sensor should be able to capture fingerprint images and successfully send the images to the BBB which should be able to successfully store the unique user-specific fingerprints for identification and authentication purposes.

**Description:** The Fingerprint sensor that is required to be connected with the BBB can found on [Amazon Webpage](https://www.amazon.com/Optical-Fingerprint-Control-Mega2560-Geekstory/dp/B07BQ9VNWR/ref=sr_1_2?keywords=fingerprint+sensor+for+raspberry+pi&qid=1572477339&sr=8-2). The Fingerprint sensor requires a UART connection with the BBB to run the scripts to capture unique user-specific fingerprints when a user is detected on the sensor. Eventually, the data collected by the BBB from the Fingerprint sensor as unique images will be stored in a file on the BBB. The stored data may be used by some other process running on the BBB.

**Open-source references:** 

| Hardware Interface   | Open-source project reference links                                 | Packages to be included | Implementation Details |
| -------------------- | ------------------------------------------------------------------- | ----------------------- | ------------ |
| BBB - Fingerprint sensor             | References: [1]() | NA | [Page]() |

**Repository:** [Source Application Repository](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7)

**DoD:** The following set of tasks will have to be successfully performed as a definition of done:

1. Log "Fingerprint sensor connected" when the Fingerprint sensor is connected with the BBB and the init script is run.
2. Log "Fingerprint sensor not detected" upon system startup if the Fingerprint sensor is not connected and/or the user requests from the user-space terminal for Fingerprint sensor service termination.
3. Log "Fingerprint sensor disconnected" upon request from the user-space using the terminal for the service termination and successful detection of the Fingerprint sensor connection with the BBB.
4. Log "User detected..." when the Fingerprint sensor is connected to the BBB and a user finger is pressed against the sensor.
5. Log "Unique fingerprints temporarily stored" when the Fingerprint sensor is connected to the BBB and multiple user fingerprints are collected by the sensor and the user-specific unique fingerprints are stored on the BBB.
6. Log "Enter user name" when the Fingerprint sensor is able to successfully store the unique fingerprints collected by the sensor specific to a user for which the BBB will ask for a user name without which the system would drop the stored fingerprints. 
7. Log "Unique fingerprints added" when the unique fingerprints are permanently stored and a user name is successfully attached with it by the BBB while there is a successful connection with the Fingerprint sensor.
8. Log "Type user name to delete data" when the user requests from the command line to delete the fingerprint data associated with a particular user name.

**Comment by dwalkes** [comment]
@sast7580 see comments to @MacRush7 in cu-ecen-5013/final-project-assignment-sast7580/issues/1  I don't see the detail here which convinces me you are ready to start writing code.

DoD verifiction should be action/verification, something like:
Log message "Fingerprint hardware detected" should be printed when the _application name_ application is run on hardware with a finger print hardware senor attached.
Log message "Fingerprint harware not detected" should be printed when the _application name_ application is run on hardware with no fingerprint hardware sensor attached.
Log messages should contain _insert relevant detail_ when a finger is placed on the reader.

In general I suspect the scope is too much for the first sprint and you should focus on understanding what open source components you plan to leverage and how to leverage them.  See also the comments in the project overview wiki.

**Comment by sast7580** [comment]
Sprint 1: fingerprint module not yet complete.  Bug in code will not allow a file to be opened.  Tested the pins using the checkButton() function in userspace.  Both the button and the led are correctly wired and functioning correctly.  Issue with the rpi build of buildroot.  Will not be able to test kernel space without functioning rpi buildroot.

**Comment by dwalkes** [comment]
@sast7580 please update the DoD to match what you actually completed with this task and reference the task where remaining issues have been moved.
Please reach out during office hours regarding sdcard programming issues.

**Comment by steveantony5** [comment]
@sast7580  Are you using linux for RPI. Because I assume you are using BBB with linux. I had the question whether you will be running linux on Rpi too. @MacRush7 said that RPi will be running on Raspbian OS. 
Also the issue says as interfacing Finger print with BBB.
If that is the case, I am confused why have you mentioned "rpi build of Buildroot".
Are you planning to have linux on RPi ? Also are you interfacing Fingerprint with Rpi?

**Comment by steveantony5** [comment]
@sast7580  Also is this task completed? As per sprint, it says as completed. Is Finger print sensor working with BBB?

**Comment by sast7580** [comment]
It was closed for sprint one since it was partially completed and the
uncompleted porton moved to a new issue for sprint 2.  The fingerprint
sensor was coded for rpi and will be recoded for bbb if I can ever get it
to build.
