### ISSUE TITLE
GSM Module device driver

### ISSUE THREAD

**Issue by MacRush7** [cu-ecen-5013/final-project-assignment-sast7580#5]
**Task:** Develop an interface for connecting the GSM module with the BBB. The GSM module should be able to send/receive text messages sent to/from a remote cellular connection and display those text messages.

**Description:** The GSM module that is required to be connected with the BBB can found on [Amazon Webpage](https://www.amazon.com/Development-Antenna-Support-Raspberry-Geekstory/dp/B079FN45FB/ref=sr_1_3?crid=1OLCSE2UZ7S84&keywords=gsm+module+raspberry+pi&qid=1572476924&sprefix=gsm+module+ras%2Caps%2C175&sr=8-3). The GSM module requires a SPI connection with the BBB to run the scripts to send/receive text messages to/from remote cellular connections. Eventually, the data collected by the BBB from the GSM module as text messages will be echoed back on the terminal and will be stored in a file on the BBB. The stored data may be used by some other process running on the BBB.

**Open-source references:**

| Hardware Interface   | Open-source project reference links                                 | Packages to be included | Implementation Details |
| -------------------- | ------------------------------------------------------------------- | ----------------------- | ------------ |
| BBB - GSM module             | References: [1]() | TBD | [Page]() |

**Repository:** [Source Application Repository](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7)

**DoD:** The following set of tasks will have to be successfully performed as a definition of done:

1. Log "GSM module connected" when the GSM module is connected with the BBB and the GSM init script is run.
2. Log "GSM module not detected" upon system startup if the GSM module is not connected and/or the user requests from the user-space terminal for GSM service termination.
3. Log "GSM module disconnected" upon request from the user-space using the terminal for the service termination and successful detection of GSM module connection with the BBB.
4. Log "GSM Received: xyz..." where xyz... is the text message successfully received by the GSM module from a remote cellular connection upon successful connection of the GSM module with the BBB.
5. Log "GSM Sent: xyz..." where xyz... is the message string entered by the user from the user-space terminal on the BBB which is then sent by the GSM module to the remote cellular connection that is pre-defined in the script upon successful command invocation and connection between the GSM module and the BBB.
6. Log "GSM Send Error" when a send-message command request from the user-space fails and the message is not sent from the GSM module to the pre-defined remote cellular connection. 
7. Log "GSM Store Error" when the BBB fails to store the message string that is sent/received from the GSM module.

**Comment by steveantony5** [comment]
@MacRush7  As per block diagram, GSM is interfaced with Rpi. Here is it said as it would be interfaced with BBB.

**Comment by MacRush7** [comment]
@steveantony5 Updated the block diagram. GSM is now shown to be interfaced with the BBB node. Thanks.

**Comment by MacRush7** [comment]
This issue was not worked upon. Instead, I have attempted to implement an NFC module to be connected with the Buildroot node.
