### ISSUE TITLE
BBB - RPi Interface (BT / UART)

### ISSUE THREAD

**Issue by MacRush7** [cu-ecen-5013/final-project-assignment-sast7580#8]
**Task:** Integrate AESD rpi with the rpi client that will a flow of data from the rpi to the AWS cloud platform. 

**Description:** The connection of the AESD rpi with the client rpi will be tentatively done using the UART protocol between the two hardware platforms.

**Open-source references:**

| Hardware Interface   | Open-source project reference links                                 | Packages to be included |
| -------------------- | ------------------------------------------------------------------- | ----------------------- |
| AESD rpi - client rpi Interface             | References: [1]() | TBD | [Page]() |

**Repository:** [Source Application Repository](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7)

**DoD:** The following set of tasks will have to be successfully performed as a definition of done:

1. Log "RPi connected" when the AESD rpi is connected with the client rpi and the init script is run upon system startup.
2. Log "RPi not detected" upon system startup if the rpi is not connected and/or the user requests from the user-space terminal for rpi connection termination.
3. Log "RPi disconnected" upon request from the user-space using the terminal for the service termination and successful detection of the client rpi connection with the AESD rpi.
4. Log "Message Received: xyz..." where xyz... is the string message successfully received by the AESD rpi from the client rpi module.
5. Log "Message Sent: xyz..." where xyz... is the message string entered by the user from the user-space terminal on the AESD rpi which is then sent to the client rpi.
6. Log "AESD rpi Send Error" when a send-message command request from the user-space fails and the message is not sent from the AESD rpi to the client rpi.
7. Log "AESD rpi Store Error" when the AESD rpi fails to store the message string that is sent/received from the client rpi.

**Comment by steveantony5** [comment]
@MacRush7 One node in the block diagram is specified as Rpi. Please specify the other node as BBB. Also update the Hardware Platform section as it says as 2 BBB.

**Comment by MacRush7** [comment]
This issue was not worked upon. The reason was that we had problems running our scripts on Buildroot, on Beaglebone Black. Given, that we shifted to using Raspberry Pi for Buildroot and eventually did not end up working on this issue at all. However, we have attempted to implement wireless NRF based communication between two boards but haven't implemented it as part of integration. Thanks.
