### ISSUE TITLE
Local MySQL Database

### ISSUE THREAD

**Issue by MacRush7** [cu-ecen-5013/final-project-assignment-sast7580#9]
**Task:** Implement MySQL package on Buildroot node.

**Description:** The MySQL server should be able to accept data for storage and give out data when a script requires it. For example, the RFID sensor can send the RFID user name and unique ID to the MySQL server for storage and the MySQL server can return this data to the node whenever it requires. 

**Open-source references:**

| Hardware Interface   | Open-source project reference links                                 | Packages to be included | Implementation Details |
| -------------------- | ------------------------------------------------------------------- | ----------------------- | ------------ |
| rpi- MySQL DB             | References: References: [1](https://mariadb.com/kb/en/library/cross-compiling-mariadb/), [2](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html?highlight=linker#cross-compiling-for-linux), [3](https://elinux.org/images/2/27/Buildroot.pdf) | MySQL Server Package [[Reference]](https://bootlin.com/pub/conferences/2014/elc/petazzoni-buildroot-whats-new/petazzoni-buildroot-whats-new.pdf) | [MariaDB Documentation](https://mariadb.com/kb/en/library/cross-compiling-mariadb/) | MySQL Server Package [[Reference]](https://bootlin.com/pub/conferences/2014/elc/petazzoni-buildroot-whats-new/petazzoni-buildroot-whats-new.pdf) | [BBB - MySQL (MariaDB) Implementation](https://github.com/cu-ecen-5013/final-project-assignment-sast7580/wiki/BBB-MySQL-(MariaDB)-Implementation) |

**Repository:** [Source Application Repository](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7)

**DoD:** The following set of tasks will have to be successfully performed as a definition of done:

1. Log "MySQL Server available" upon system startup if the MySQL Server is up and running.
2. Log "MySQL DB updated" when a script writes data to the MySQL database.
4. Log "MySQL DB read" when a script reads data from the MySQL database.
5. Log "MySQL DB deleted" when the script receives a termination signal (e.g Ctrl+C).

**Comment by MacRush7** [comment]
**Issue Updates:** I could partially complete the implementation as presented on the [page](https://github.com/cu-ecen-5013/final-project-assignment-sast7580/wiki/BBB-MySQL-(MariaDB)-Implementation). Therefore, this will be moved to Sprint-2.

**Comment by dwalkes** [comment]
@MacRush7 I don't think there was anything actually completed with this task due to the issues mentioned above.  No need for a separate wiki page for this, I'd put the detail here in the issue, and I wouldn't open another issue with the same content.
Regarding the error, my suspicion is that you didn't perform a clean build when switching project hardware and therefore your cross compile toolchain isn't setup properly.

**Comment by steveantony5** [comment]
@MacRush7  @sast7580  As per the block diagram, it is said that database MySQL is being set up on RPi. But as per the issue, it seems as being done on BBB. Please align your work with the block diagram.

**Comment by MacRush7** [comment]
**Issue Updates:** After successfully running the test MySQL script (named rpi-mysql.py) for the RPI node, I am marking this issue complete since the DoD has been met. Detailed requirements as mentioned in the DoD will be met when the project is integrated since there will be inter-process communication then. Thanks.

**Comment by dwalkes** [comment]
@MacRush7 
> After successfully running the test MySQL script (named rpi-mysql.py) for the RPI node, I am marking this issue complete since the DoD has been met

Please update your DoD to reference the MySQL script and specific command lines/observations used for test

As I understand it, the https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/blob/master/rpi-mysql.py script was created for EID with some minor changes for this course, is that correct?  Therefore the work associated with this task was just installing the script into the root filesystem and adding the mysql package to buildroot configuration?

I expected to see mysql in the buildroot configuration at https://github.com/cu-ecen-5013/final-project-assignment-sast7580/pull/15/files but don't see it there.  Did you forget to save_config.sh?

**Comment by MacRush7** [comment]
@dwalkes 

Thank you for the clarification. Yes, the script does not contain significant changes since the underlying design was same, as mentioned in the script. I was initially attempting to add the MySQL package to buildroot for my sprint-2 goals. I had problems building it since there were a lot of library dependencies and in addition to that, I was facing problem with the Git TI download instance during the build attempts. 

Later, I heard from @steveantony5 and he suggested me to rather focus on implementing some kind of wireless connectivity for the BBB and RPI nodes and implement the MySQL package on the RPI node since that would save time and problems with the build. That said, I did change the task statement for this issue (specified it for the RPi node and not the BBB node) and therefore I did not implement it for the BBB running buildroot. I wrote the script to showcase that a MySQL DB (if enabled using MariaDB) can be created on the RPI node and can be interacted with during project integration phase in sprint-3. So, that was the reason why I did not have it in the buildroot configuration.

**Comment by steveantony5** [comment]
@dwalkes I suggested Rushi to work on some additional features like wireless connectivity or something like that as it would add value when explaining in interviews instead of working on SQL database on buildroot. Having database on buildroot would not make a huge impact in explaining at interviews when compared to additional features but if you wish to learn and explore MySql on buildroot, go for it.

**Comment by dwalkes** [comment]
@MacRush7 thanks for the clarification.
My issue here is that it appears the description tracks what you originally planned to do as opposed to what you did, and the DoD doesn't match what you did.
So I recommend either re-opening the issue (if you plan to learn and explore MySQL as a part of the project, probably doubtful since there's not much time left) or changing the description to match what you actually did (make minor changes to a script used for EID as an example of what might be possible with your project if you were to include a database) along with some reason why you didn't include the database ("I had problems building it since there were a lot of library dependencies").  In other words, make it so myself and Student Assistants don't need to dig through code and comments in your issue to figure out what you actually did with the issue, make it transparent, upfront and easily distinguishable from the description of the issue.  Does this make sense?  If not, please meet me on slack to discuss.

**Comment by MacRush7** [comment]
@dwalkes Thanks for your guidance. 
I have been able to successfully build Buildroot files for MySQL (MariaDB) server. That said, I am now planning to complete adding the MySQL package to my Buildroot as part of sprint-3 deliverables. I will work on this issue during sprint-3 as well to meet the exact DoD as mentioned above in the issue description.

For details regarding what was achieved as part of sprint-2, please see below. I have added extra comments regarding modified DoD accomplishments for sprint-2 regarding this issue based on the guidelines posted earlier.

**Tasks completed for sprint-2:**

The [python script](https://github.com/cu-ecen-5013/final-project-assignment-MacRush7/blob/master/rpi-mysql.py) demonstrates the use of a MySQL (MariaDB) server by connecting to the localhost database (i.e. mydatabase) that was created before running the script. This script was written for a Raspberry Pi because there were issues building buildroot files because of the problems with the git ti server. To save time, I wrote this script for testing the MySQL package on the RPi node.

The script meets the following criteria although does not log messages as mentioned in the DoD:

1. The script connects to the localhost database (i.e. mydatabase).
2. The script creates a MySQL table for testing (i.e. mytable).
3. The script adds data columns to the created database table and stores some predefined values demonstrating a way of storing the information acquired from the RFID sensor in the MySQL database.
4. The script prints out the data stored in the associated MySQL table of the connected MySQL database.
5. The script drops the table so that the script can be executed repeatedly without any errors for existing tables.

The whole idea behind this work is to demonstrate how the MySQL database will be used eventually during the project integration and testing.

If there are any queries regarding the above comments, please let me know. Thanks.

**Comment by dwalkes** [comment]
@MacRush7 

> The python script demonstrates the use of a MySQL (MariaDB) server by connecting to the localhost database (i.e. mydatabase) that was created before running the script. This script was written for a Raspberry Pi because

And, based on the comments from @steveantony5 in email, the script is based on EID, meaning there was no meaningful work done for this course as a part of resolving this issue.  Is that correct?  You'll recall I've asked several times to be very clear about which portions of your project you are developing for this course and which portions are coming from other courses.  Please **edit the description** to make this clear.  

When you mark a task as resolved without clearly specifying what you've done but instead include statements in the description which don't match what you did this runs the risk of making it look like you are attempting to inflate the amount of work you've done on a specific task.

> The script meets the following criteria although does not log messages as mentioned in the DoD:

If all of this was a part of the script you wrote for EID then please do not include this in the DoD.  What I want to know in the description of this task is:

1) The work you did **for AESD** in completion of the issue, including how you leveraged work from other courses.
2) How a student assistant or myself could verify this work.

**Comment by MacRush7** [comment]
@dwalkes I am sorry for the confusion from my end. I have updated the issue description to clarify everything. If there is anything unclear, please let me know. Thanks.

**Comment by MacRush7** [comment]
For the final sprint, I have implemented a similar script as submitted for sprint-2 that attempts to store alerts in the local database. However, even after the MariaDB package was added in Buildroot menuconfig successfully, I was unable to run my final script on Buildroot - as it was unable to import the MySQLdb library.
